name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run tests (optional)
        run: echo "No tests yet"

      - name: Build Docker image
        run: docker build -t cicd-app .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag cicd-app ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:latest